apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: adder
  name: adder
  namespace: b6026042
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adder
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: adder
    spec:
      containers:
      - image: chanwit/adder
        imagePullPolicy: Always
        name: adder
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
