apiVersion: v1
kind: Service
metadata:
  labels:
    app: front
  name: front
  namespace: default
spec:
  externalTrafficPolicy: Cluster
  ports:
  - port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app: front
  sessionAffinity: None
  type: LoadBalancer
