apiVersion: v1
kind: Service
metadata:
  labels:
    app: suber
  name: suber
  namespace: b6026042
spec:
  externalTrafficPolicy: Cluster
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: suber
  sessionAffinity: None
  type: LoadBalancer
