apiVersion: v1
kind: Service
metadata:
  labels:
    app: backend
  name: backend
  namespace: default
  resourceVersion: "6682"
spec:
  externalTrafficPolicy: Cluster
  ports:
  - port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: backend
  sessionAffinity: None
  type: LoadBalancer
